// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC56g-d_I_3cmpV43_8PpNJKkskZArSrA',
    appId: '1:441606888982:web:d491f22b43dc40239b9f37',
    messagingSenderId: '441606888982',
    projectId: 'my-new-orange',
    authDomain: 'my-new-orange.firebaseapp.com',
    storageBucket: 'my-new-orange.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAghG2Bn6tWI4JzBuV_6axE237iX0Vrmk0',
    appId: '1:441606888982:android:48923729f774b8569b9f37',
    messagingSenderId: '441606888982',
    projectId: 'my-new-orange',
    storageBucket: 'my-new-orange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABayw-2h8PHtfl6nHh5o05klKDM0jVIps',
    appId: '1:441606888982:ios:2ec573fb7526f10d9b9f37',
    messagingSenderId: '441606888982',
    projectId: 'my-new-orange',
    storageBucket: 'my-new-orange.appspot.com',
    iosClientId: '441606888982-6fkfj9jo5cinr38fqqn1vkmlo7o2ju7o.apps.googleusercontent.com',
    iosBundleId: 'com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABayw-2h8PHtfl6nHh5o05klKDM0jVIps',
    appId: '1:441606888982:ios:2c94feaf3ebca1439b9f37',
    messagingSenderId: '441606888982',
    projectId: 'my-new-orange',
    storageBucket: 'my-new-orange.appspot.com',
    iosClientId: '441606888982-pkmmj5kiicih3elkqf6af6koie3q1a0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewOrange',
  );
}
